### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by mcastorena0316**
Asking for a review for my project, i believe i already realize all the requirements that are needed. Thank you

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
Hi Melissa! 
 
#### Great job!  Wow, your README is very detailed.  Looks :+1: 

Friendly reminder: You should use Github Flow in this project. 
Please take a step back read more and watch video here [Using Github Flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/).

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). Hope in the next project you can do this! 

- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

### Navbar
Great that you use  the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links and Navigation bar have a fixed position (it sticks to the top part of the screen). 

- [ ] But it should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section.

### Navigation background

- [ ] In this project you need to use CSS gradient for the background in nav. You can read about CSS Gradients [here](https://www.w3schools.com/css/css3_gradients.asp)

### Footer
Great that you use the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer

### Make these changes and submit another code review request.

*If you have any questions, let me know here or on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by mcastorena0316** [comment]
Hi, i already change the nav bar with buttons as you requested, i passed the validator  and change the nav bar background for a gradient. So i am ready for a new review. Hopefully this one gets approved.

**Comment by shloch** [comment]
### Great job @mcastorena0316 with the corrections  👏👏

Challenge fully respected

### **The project is approved**
You can merge this pull request

Happy coding

**Pull request merged**
